# Python Tutorial Exercises

These python tutorial exercises is for EECS 545 Fall 2020. 
Instructor: Clayton Scott.
GSIs: Haonan Zhu, Tony Zhang, Conrad Hougen, Thomas Huang.

Note: There can be multiple solutions to each exercise; our solution is just one of them. If you solved the exercise with a different method, then great! Though, if our solution is much simpler than yours, it may be worth it to learn from our solution, since often times you will find existing functions that you didn't know about that does exactly what you want.

## Basic Python

In [ ]:
"""
Create a function called num_sum that takes as input an integer n.
Return two outputs:
1. A list of all integers that are divisible by 3 or 7 between 0
    and n inclusive.
2. The sum of the above list.
"""
# 

print()

In [ ]:
# Check against solution
print(num_sum(0))
print(num_sum(10))
print(num_sum(30))

# Solution
print("""
([0], 0)
([0, 3, 6, 7, 9], 25)
([0, 3, 6, 7, 9, 12, 14, 15, 18, 21, 24, 27, 28, 30], 214)
""")

## NumPy

### Part a) Creating NumPy arrays

In [ ]:
import numpy as np
np.random.seed(0)

"""
Create four NumPy arrays with the following conditions:
- a is a 3x2 array that consists of values sampled from a uniform
    distribution over [0,1).
- b is a 2x1 array that consists of values sampled from a standard
    normal distribution.
- c is a 2x1 array that consists of only ones.
- d is a 2x2 array that consists of only zeros with type int.
"""
# a = 
# b = 
# c = 
# d = 

print()

In [ ]:
# Check against solution
print(a)
print(b)
print(c)
print(d)

# Solution
print("""
[[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]]
[[ 0.95008842]
 [-0.15135721]]
[[1.]
 [1.]]
[[0 0]
 [0 0]]
""")

### Part b) Concatenating NumPy arrays

In [ ]:
"""
Create four NumPy arrays with the following conditions:
- e is the concatenation of b and c in the first dimension.
- f is the concatenation of b and d in the second dimension.
- Concatenate b with another array to create g such that each row of g starts
    with the number 1.
- Add two rows of zeros to a through concatenation to create h.
"""
# e = 
# f = 
# g = 
# h = 

print()

In [ ]:
# Check against solution
print(e)
print(f)
print(g)
print(h)

# Solution
print("""
[[ 0.95008842]
 [-0.15135721]
 [ 1.        ]
 [ 1.        ]]
[[ 0.95008842  0.          0.        ]
 [-0.15135721  0.          0.        ]]
[[ 1.          0.95008842]
 [ 1.         -0.15135721]]
[[0.5488135  0.71518937]
 [0.60276338 0.54488318]
 [0.4236548  0.64589411]
 [0.         0.        ]
 [0.         0.        ]]
""")

### Part c) NumPy math

In [ ]:
"""
Create five NumPy arrays with the following conditions:
- i: Compute the element-wise sum between b and c.
- j: Compute the element-wise absolute difference between b and c.
- k: Compute the inner product between the vectors b and c.
- l: Compute the outer product between the vectors b and c.
- m: Compute the matrix product between a and b.
"""
# i = 
# j = 
# k = 
# l = 
# m = 

print()

In [ ]:
# Check against solution
print(i)
print(j)
print(k)
print(l)
print(m)

# Solution
print("""
[[1.95008842]
 [0.84864279]]
[[0.04991158]
 [1.15135721]]
[[0.79873121]]
[[ 0.95008842  0.95008842]
 [-0.15135721 -0.15135721]]
[[0.41317229]
 [0.4902065 ]
 [0.30474879]]
""")

### Part d) Some more advanced exercises

In [ ]:
"""
Create three NumPy arrays with the following conditions:
- n: Subtract the mean of each column of a from a.
- o: Sort a by the values in the second column. You should
    use numpy.argsort().
- p: Create p, which is a but with the first two rows and
    first column set to the value of b. Do not modify a.
"""
# n = 
# o = 
# p = 

print()

In [ ]:
# Check against solution
print(n)
print(o)
print(p)
print(a[:2,:1])

# Solution
print("""
[[ 0.02373628  0.07986715]
 [ 0.07768615 -0.09043904]
 [-0.10142243  0.01057189]]
[[0.60276338 0.54488318]
 [0.4236548  0.64589411]
 [0.5488135  0.71518937]]
[[ 0.95008842  0.71518937]
 [-0.15135721  0.54488318]
 [ 0.4236548   0.64589411]]
[[0.5488135 ]
 [0.60276338]]
""")

## Matplotlib

In [ ]:
import matplotlib.pyplot as plt
x = np.arange(100)
y1 = np.arange(100)
y2 = np.zeros(100)
y3 = np.arange(100)[::-1]
y4 = np.abs(y3 - y1)

"""
Create a Matplotlib figure with the following conditions:
- 4 subplots in total, arranged in two rows and two columns.
- The figure has the title 'Python Tutorial Exercise'.
- Subplot 0, 0:
    - Plots y1 vs x with a solid line.
    - Subplot title is '1' with ylabel 'Subplot 1'.
    - y-axis ticks on the left side.
- Subplot 0, 1:
    - Plots y2 vs x with a dashed line.
    - Subplot title is '2' with ylabel 'Subplot 2'.
    - y-axis ticks on the right side.
- Subplot 1, 0:
    - Plots y3 vs x with a solid line.
    - ylabel 'Subplot 3' with xlabel 'x1'.
    - y-axis ticks on the left side.
- Subplot 1, 1:
    - Plots y1 vs x with a solid line.
    - ylabel 'Subplot 4' with xlabel 'x2'.
    - y-axis ticks on the right side.
"""
# 

plt.show()

print()

In [ ]:
from PIL import Image
from IPython.display import display
img = Image.open('solution_plot.png')
display(img)